max_steps = 100
output_dir = "/path/to/outputs/qwen3-32b-lora32"

[model]
name = "Qwen/Qwen3-32B"
trust_remote_code = true
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"
tp = 1 #2

[model.experimental.lora]
rank = 32

[model.ac]
freq = 1

[model.ac_offloading]
pin_memory = true
max_inflight_activations = 1

[data]
name = "parsed/sayvant-final"
batch_size = 8
seq_len = 8192

[optim]
lr = 2e-4

[wandb]
project = "sayvant"


