max_steps = 100
output_dir = "outputs/qwen3-4b-lora32"

[model]
name = "Qwen/Qwen3-4B"
trust_remote_code = true
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[model.experimental.lora]
rank = 32

[data]
name = "parsed/sayvant-final"
batch_size = 8
seq_len = 16384
format = "text"

[optim]
lr = 2e-4

[wandb]
project = "sayvant"


